"""relationship column removed from s3 bucket

Revision ID: 685deb6d155d
Revises: ba38a9d89ef2
Create Date: 2025-08-22 18:51:58.939734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685deb6d155d'
down_revision: Union[str, Sequence[str], None] = 'ba38a9d89ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
