"""Add new columns or modify ec2_instances name_tag

Revision ID: 77d92d8c8979
Revises: d2000b927c63
Create Date: 2025-08-22 12:51:48.908688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d92d8c8979'
down_revision: Union[str, Sequence[str], None] = 'd2000b927c63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ec2_instances', 'name_tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ec2_instances', sa.Column('name_tag', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
