"""modify  columns ec2_instances network_interface_id size

Revision ID: 9fc100b2fc38
Revises: a0631b422f4a
Create Date: 2025-08-22 16:36:29.893442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc100b2fc38'
down_revision: Union[str, Sequence[str], None] = 'a0631b422f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ec2_instances', 'network_interface_id',
               existing_type=sa.VARCHAR(length=96),
               type_=sa.String(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ec2_instances', 'network_interface_id',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=96),
               existing_nullable=True)
    # ### end Alembic commands ###
