"""Add new columns ec2_instances

Revision ID: a0631b422f4a
Revises: 77d92d8c8979
Create Date: 2025-08-22 15:53:52.930155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0631b422f4a'
down_revision: Union[str, Sequence[str], None] = '77d92d8c8979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ec2_instances', sa.Column('private_dns_name', sa.String(length=128), nullable=True))
    op.add_column('ec2_instances', sa.Column('public_dns_name', sa.String(length=128), nullable=True))
    op.add_column('ec2_instances', sa.Column('thirty_days_avg', sa.String(length=10), nullable=True))
    op.add_column('ec2_instances', sa.Column('thirty_days_max', sa.String(length=10), nullable=True))
    op.add_column('ec2_instances', sa.Column('thirty_days_min', sa.String(length=10), nullable=True))
    op.add_column('ec2_instances', sa.Column('sixty_days_avg', sa.String(length=10), nullable=True))
    op.add_column('ec2_instances', sa.Column('sixty_days_max', sa.String(length=10), nullable=True))
    op.add_column('ec2_instances', sa.Column('sixty_days_min', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ec2_instances', 'sixty_days_min')
    op.drop_column('ec2_instances', 'sixty_days_max')
    op.drop_column('ec2_instances', 'sixty_days_avg')
    op.drop_column('ec2_instances', 'thirty_days_min')
    op.drop_column('ec2_instances', 'thirty_days_max')
    op.drop_column('ec2_instances', 'thirty_days_avg')
    op.drop_column('ec2_instances', 'public_dns_name')
    op.drop_column('ec2_instances', 'private_dns_name')
    # ### end Alembic commands ###
