"""added new table s3_buckets with few columns

Revision ID: ba38a9d89ef2
Revises: 9fc100b2fc38
Create Date: 2025-08-22 18:48:12.627854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba38a9d89ef2'
down_revision: Union[str, Sequence[str], None] = '9fc100b2fc38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s3_buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucket_name', sa.String(length=128), nullable=False),
    sa.Column('creation_date', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('get_bucket_versioning', sa.JSON(), nullable=True),
    sa.Column('tag_properties', sa.JSON(), nullable=True),
    sa.Column('lifecycle_policy', sa.String(length=256), nullable=True),
    sa.Column('classifiable_object_count', sa.String(length=24), nullable=True),
    sa.Column('classifiable_size_bytes', sa.String(length=32), nullable=True),
    sa.Column('last_update', sa.String(length=64), nullable=True),
    sa.Column('account_id', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket_name')
    )
    op.add_column('ec2_instances', sa.Column('provider', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ec2_instances', 'provider')
    op.drop_table('s3_buckets')
    # ### end Alembic commands ###
