"""initial aws finops tables

Revision ID: bbb9368aa093
Revises: 
Create Date: 2025-08-21 16:02:56.248895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb9368aa093'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('account_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('org_unit', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('ec2_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.String(length=32), nullable=False),
    sa.Column('instance_type', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('account_id', sa.String(length=32), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('name_tag', sa.String(length=128), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('other_prop', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ec2_instances')
    op.drop_table('accounts')
    # ### end Alembic commands ###
