"""Add new columns or modify ec2_instances

Revision ID: d2000b927c63
Revises: bbb9368aa093
Create Date: 2025-08-21 18:17:30.648600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2000b927c63'
down_revision: Union[str, Sequence[str], None] = 'bbb9368aa093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ec2_instances', sa.Column('creation_time', sa.String(length=64), nullable=True))
    op.add_column('ec2_instances', sa.Column('state_code', sa.String(length=32), nullable=True))
    op.add_column('ec2_instances', sa.Column('last_transition_date', sa.String(length=64), nullable=True))
    op.add_column('ec2_instances', sa.Column('aging', sa.String(length=64), nullable=True))
    op.add_column('ec2_instances', sa.Column('last_transition_reason', sa.String(length=128), nullable=True))
    op.add_column('ec2_instances', sa.Column('launch_update_time', sa.String(length=64), nullable=True))
    op.add_column('ec2_instances', sa.Column('availability_zone', sa.String(length=128), nullable=True))
    op.add_column('ec2_instances', sa.Column('mac_address', sa.String(length=64), nullable=True))
    op.add_column('ec2_instances', sa.Column('network_interface_id', sa.String(length=96), nullable=True))
    op.add_column('ec2_instances', sa.Column('private_ip_address', sa.String(length=64), nullable=True))
    op.add_column('ec2_instances', sa.Column('public_ip_address', sa.String(length=64), nullable=True))
    op.add_column('ec2_instances', sa.Column('network_interface_attachment_id', sa.String(length=64), nullable=True))
    op.add_column('ec2_instances', sa.Column('usage_operation', sa.String(length=64), nullable=True))
    op.add_column('ec2_instances', sa.Column('platform', sa.String(length=64), nullable=True))
    op.add_column('ec2_instances', sa.Column('architecture', sa.String(length=20), nullable=True))
    op.add_column('ec2_instances', sa.Column('subnet_id', sa.String(length=32), nullable=True))
    op.add_column('ec2_instances', sa.Column('vpc_id', sa.String(length=32), nullable=True))
    op.add_column('ec2_instances', sa.Column('image_id', sa.String(length=64), nullable=True))
    op.add_column('ec2_instances', sa.Column('security_groups', sa.String(length=128), nullable=True))
    op.add_column('ec2_instances', sa.Column('tag_properties', sa.JSON(), nullable=True))
    op.add_column('ec2_instances', sa.Column('instance_name', sa.String(length=128), nullable=True))
    op.add_column('ec2_instances', sa.Column('root_device_type', sa.String(length=64), nullable=True))
    op.add_column('ec2_instances', sa.Column('volume_id', sa.String(length=64), nullable=True))
    op.add_column('ec2_instances', sa.Column('volume_type', sa.String(length=64), nullable=True))
    op.add_column('ec2_instances', sa.Column('volume_size', sa.String(length=20), nullable=True))
    op.add_column('ec2_instances', sa.Column('volume_iops', sa.String(length=20), nullable=True))
    op.add_column('ec2_instances', sa.Column('volume_instance_name', sa.String(length=128), nullable=True))
    op.add_column('ec2_instances', sa.Column('volume_device', sa.String(length=64), nullable=True))
    op.add_column('ec2_instances', sa.Column('volume_status', sa.String(length=64), nullable=True))
    op.add_column('ec2_instances', sa.Column('volume_encrypted', sa.String(length=64), nullable=True))
    op.add_column('ec2_instances', sa.Column('volume_attach_time', sa.String(length=64), nullable=True))
    op.add_column('ec2_instances', sa.Column('volume_delete_on_termination', sa.String(length=64), nullable=True))
    op.add_column('ec2_instances', sa.Column('network_attach_time', sa.String(length=64), nullable=True))
    op.add_column('ec2_instances', sa.Column('ebs_optimized', sa.String(length=64), nullable=True))
    op.add_column('ec2_instances', sa.Column('monitoring_state', sa.String(length=64), nullable=True))
    op.drop_column('ec2_instances', 'other_prop')
    op.drop_column('ec2_instances', 'properties')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ec2_instances', sa.Column('properties', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ec2_instances', sa.Column('other_prop', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('ec2_instances', 'monitoring_state')
    op.drop_column('ec2_instances', 'ebs_optimized')
    op.drop_column('ec2_instances', 'network_attach_time')
    op.drop_column('ec2_instances', 'volume_delete_on_termination')
    op.drop_column('ec2_instances', 'volume_attach_time')
    op.drop_column('ec2_instances', 'volume_encrypted')
    op.drop_column('ec2_instances', 'volume_status')
    op.drop_column('ec2_instances', 'volume_device')
    op.drop_column('ec2_instances', 'volume_instance_name')
    op.drop_column('ec2_instances', 'volume_iops')
    op.drop_column('ec2_instances', 'volume_size')
    op.drop_column('ec2_instances', 'volume_type')
    op.drop_column('ec2_instances', 'volume_id')
    op.drop_column('ec2_instances', 'root_device_type')
    op.drop_column('ec2_instances', 'instance_name')
    op.drop_column('ec2_instances', 'tag_properties')
    op.drop_column('ec2_instances', 'security_groups')
    op.drop_column('ec2_instances', 'image_id')
    op.drop_column('ec2_instances', 'vpc_id')
    op.drop_column('ec2_instances', 'subnet_id')
    op.drop_column('ec2_instances', 'architecture')
    op.drop_column('ec2_instances', 'platform')
    op.drop_column('ec2_instances', 'usage_operation')
    op.drop_column('ec2_instances', 'network_interface_attachment_id')
    op.drop_column('ec2_instances', 'public_ip_address')
    op.drop_column('ec2_instances', 'private_ip_address')
    op.drop_column('ec2_instances', 'network_interface_id')
    op.drop_column('ec2_instances', 'mac_address')
    op.drop_column('ec2_instances', 'availability_zone')
    op.drop_column('ec2_instances', 'launch_update_time')
    op.drop_column('ec2_instances', 'last_transition_reason')
    op.drop_column('ec2_instances', 'aging')
    op.drop_column('ec2_instances', 'last_transition_date')
    op.drop_column('ec2_instances', 'state_code')
    op.drop_column('ec2_instances', 'creation_time')
    # ### end Alembic commands ###
